# Generated by Django 3.0 on 2021-06-10 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checksheet', '0004_auto_20210610_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updatesheet',
            old_name='content_type',
            new_name='contenttype',
        ),
    ]
