# Generated by Django 3.0 on 2021-06-10 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checksheet', '0006_auto_20210610_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatesheet',
            name='车型',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checksheet.CarType', verbose_name='车型'),
        ),
    ]
