# Generated by Django 3.0 on 2021-06-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checksheet', '0007_auto_20210610_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatesheet',
            name='车型',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
