# Generated by Django 3.0 on 2021-06-10 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('checksheet', '0008_auto_20210610_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatesheet',
            name='contenttype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
