# Generated by Django 3.0 on 2021-06-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checksheet', '0009_auto_20210610_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatesheet',
            name='SNPs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='container',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='manage_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='material',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='standard_spm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='thickness',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='加工日',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
