# Generated by Django 3.0 on 2021-06-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checksheet', '0010_auto_20210610_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatesheet',
            name='卷材代号',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
