# Generated by Django 3.0 on 2021-06-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checksheet', '0011_updatesheet_卷材代号'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatesheet',
            name='confirmation_fre1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='confirmation_fre2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='confirmation_fre3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='confirmation_fre4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='confirmation_fre5',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='confirmation_fre6',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='confirmation_fre7',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='confirmation_meth1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='confirmation_meth2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='confirmation_meth3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='confirmation_meth4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='confirmation_meth5',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='confirmation_meth6',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='confirmation_meth7',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='cushion_set',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='diehight_set',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='draw_set',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='manage_pj1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='manage_pj2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='manage_pj3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='manage_pj4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='manage_pj5',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='manage_pj6',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='manage_pj7',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='occur_day1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='occur_day2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='occur_day3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='occur_reason1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='occur_reason2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='occur_reason3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='unqualified1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='unqualified2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='unqualified3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='不良数',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='人手替换',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='合格数',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='拉延模压力',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='机械修理',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='模具修理',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='模具高度',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='气垫顶出高度',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='生产数',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
