# Generated by Django 3.0 on 2021-06-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checksheet', '0012_auto_20210611_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatesheet',
            name='cushion_set',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='updatesheet',
            name='diehight_set',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='updatesheet',
            name='draw_set',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='updatesheet',
            name='拉延模压力',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='updatesheet',
            name='模具高度',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='updatesheet',
            name='气垫顶出高度',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
