# Generated by Django 3.0 on 2021-06-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checksheet', '0014_auto_20210611_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatesheet',
            name='standard_spm',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='updatesheet',
            name='加工SPM',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
