# Generated by Django 3.0 on 2021-06-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checksheet', '0019_updatesheet_确认点位'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatesheet',
            name='备注',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
