# Generated by Django 3.0 on 2021-06-18 05:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checksheet', '0020_updatesheet_备注'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checksheet',
            old_name='content',
            new_name='content1',
        ),
        migrations.AddField(
            model_name='checksheet',
            name='content2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
