# Generated by Django 3.0 on 2021-06-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checksheet', '0021_auto_20210618_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updatesheet',
            old_name='确认点位',
            new_name='确认点位1',
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='确认点位2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
