# Generated by Django 3.0 on 2021-06-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checksheet', '0024_checksheetbl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckSheetBL',
        ),
    ]
