# Generated by Django 3.0 on 2021-06-28 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checksheet', '0026_checksheetbl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checksheetbl',
            name='容器',
        ),
    ]
