# Generated by Django 3.0 on 2021-06-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checksheet', '0027_remove_checksheetbl_容器'),
    ]

    operations = [
        migrations.AddField(
            model_name='checksheetbl',
            name='加工模高设定',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
