# Generated by Django 3.0 on 2021-06-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checksheet', '0028_checksheetbl_加工模高设定'),
    ]

    operations = [
        migrations.AddField(
            model_name='checksheet',
            name='标准材料宽度',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='checksheet',
            name='进给量',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='CheckSheetBL',
        ),
    ]
