# Generated by Django 3.0 on 2021-07-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checksheet', '0029_auto_20210628_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatesheet',
            name='标准材料宽度',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='updatesheet',
            name='进给量',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
