# Generated by Django 3.0 on 2021-07-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checksheet', '0030_auto_20210702_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatesheet',
            name='模具检查清扫',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
