# Generated by Django 3.0 on 2021-07-02 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checksheet', '0031_updatesheet_模具检查清扫'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatesheet',
            name='模具检查清扫',
        ),
    ]
