# Generated by Django 3.0 on 2021-07-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checksheet', '0034_auto_20210702_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatesheet',
            name='SNPs',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='updatesheet',
            name='不良数',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='updatesheet',
            name='合格数',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='updatesheet',
            name='标准材料宽度',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='updatesheet',
            name='生产数',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='updatesheet',
            name='进给量',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
